### ISSUE TITLE
Detected blocking call on HA restart (sensor.py line 44)

### ISSUE THREAD

**Issue by tramperb** [mk-maddin/wattpilot-HA#46]
**Describe the issue you are experiencing**
Although all entities, that I use, are still available, the following error occurs on restart of HA.

```
Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 9:06:55 PM (5 occurrences)
Last logged: 9:06:55 PM

Detected blocking call to open inside the event loop by custom integration 'wattpilot' at 
custom_components/wattpilot/sensor.py, line 44: with 
open(os.path.dirname(os.path.realpath(__file__))+'/'+platform+'.yaml', 'r') as stream: (offender: 
/config/custom_components/wattpilot/sensor.py, line 44: with 
open(os.path.dirname(os.path.realpath(__file__))+'/'+platform+'.yaml', 'r') as stream:), please report it to the author
 of the 'wattpilot' custom integration Traceback (most recent call last): File "<frozen runpy>", line 198, in 
_run_module_as_main File "<frozen runpy>", line 88, in _run_code File 
"/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File 
"/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File
 "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return 
loop.run_until_complete(setup_and_run_hass(runtime_config)) File 
"/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File 
"/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File 
"/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File 
"/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File 
"/usr/src/homeassistant/homeassistant/config_entries.py", line 2055, in async_forward_entry_setup return await
 self._async_forward_entry_setup(entry, domain, True) File 
"/usr/src/homeassistant/homeassistant/config_entries.py", line 2081, in _async_forward_entry_setup await
 entry.async_setup(self.hass, integration=integration) File 
"/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await 
component.async_setup_entry(hass, self) File 
"/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_setup_entry return 
await component.async_setup_entry(entry) File 
"/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_setup_entry return 
await self._platforms[key].async_setup_entry(config_entry) File 
"/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry return await 
self._async_setup_platform(async_create_setup_awaitable) File 
"/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform 
awaitable = create_eager_task(awaitable, loop=hass.loop) File 
"/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, 
loop=loop, name=name, eager_start=True) File "/config/custom_components/wattpilot/sensor.py", line 44, in 
async_setup_entry with open(os.path.dirname(os.path.realpath(__file__))+'/'+platform+'.yaml', 'r') as stream:

```

**What version of Home Assistant Core is installed**
Updated from 2024.5.3 to 2024.6.3
I don't believe the error occurred with 2024.5.3 (but can't be certain).

**What version of Wattpilot integration is installed**
Release 0.1.9

**What version of Wattpilot are you using**
22KW-V2

**Comment by mk-maddin** [comment]
thanks for reporting.
file operations are always blocking - even when wrapped within hass async function.
I will try to re-implement this using aiofiles: https://github.com/Tinche/aiofiles

**Comment by mk-maddin** [comment]
should be fixed as of: https://github.com/mk-maddin/wattpilot-HA/commit/d7ad72a7e3168ba59cb4661e0a9b2012bf354756
Can you please verify and confirm/give feedback?

Thanks

**Comment by tramperb** [comment]
Thanks, Martin - downloaded the 6 files, copied to the custom components / wattpilot directory, restarted HA - fixed.

There is, however, another error (or two?).  Introduced at the same time as this issue, I thought it might have been related.  As it didn't go away, I'll log it as a separate bug.

Thanks again !

**Comment by mk-maddin** [comment]
fixed with https://github.com/mk-maddin/wattpilot-HA/commit/d7ad72a7e3168ba59cb4661e0a9b2012bf354756

will be part of next release
